name: Tahoe Poon
favicon: null
layout_spectrum: 0
typography_spectrum: 0.530616324627772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9d1d4'
    - '#150d0a'
    - '#52544f'
    - '#886b66'
    - '#3a85c0'
  brandStrength: 0.8309831412043422
  lightness: 0.6161327110603452
  saturation: 0.5812092204578221
  rhythmicContrast: 0.5723266939166933
purpose: []
